services:
  - type: web
    name: blog-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn blogapi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blogapi.settings
